name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "An issue? Here? That's odd. I'll have someone take a look."
        pr-message: "Thanks for your first PR! Please make sure you've updated the readme so we know that you claimed that file! We SOOOOOOO appreciate your contribution!"
